-- FAX
-- SCFAXSND_TBL SND
-- SZFAXSNT_INS SNT
-- SCFAXIMG_TBL IMG
SELECT SEND_TYPE = 'FAX', SNT.JOB_SEQ, SNT.EMP_ID, SNT.USER_NAME,
       SNT.FULL_ACC_NO, SNT.ACC_NO, SNT.PRD_NO, SNT.BLC_NO, SNT.ACC_NAME_KOR,
       F_RCV_NAME_KOR = SND.RCV_COMP_KOR, SND.MEDIA_NO,
       E_RCV_NAME_KOR = '', RCV_MAIL_ADDR = '',
       SNT.REPORT_CODE, SNT.REPORT_ID, SNT.VIEW_FILENAME, 
       SUBJECT_DATA = '', MAIL_BODY_DATA = '', SND.SEND_TIME, SND.SENT_TIME,
       SND.SND_DATE, SND.DIFF_TIME, IMG.DIRECTION, IMG.TOTAL_PAGES, 
       SND.SEND_PAGE, SND.BUSY_RESND_CNT, SND.RSP_FLAG, SND.CUR_TOT_SEQ_NO, 
       SND.ERR_CODE, SND.EXT_MSG, SND.OPR_ID, SND.OPR_TIME 
FROM SCFAXSND_TBL SND 
JOIN (SELECT S.*, 
               FULL_ACC_NO = (CASE WHEN M.PRD_NO = '' THEN M.ACC_NO
                                   ELSE (CASE WHEN M.BLC_NO = '' THEN M.ACC_NO + '-' + M.PRD_NO
                                              ELSE M.ACC_NO + '-' + M.PRD_NO + '-' + M.BLC_NO
                                         END)
                              END), A.ACC_NAME_KOR,
               M.ACC_NO, M.PRD_NO, M.BLC_NO, M.JOB_TIME, M.EMP_ID, U.USER_NAME,
               R.REPORT_CODE, R.VIEW_FILENAME,
               REPORT_ID = ISNULL((SELECT RI.REPORT_ID
                                   FROM SZREPID_INS RI
                                   WHERE R.REPORT_CODE = RI.REPORT_CODE), R.REPORT_CODE)
        FROM SZFAXSNT_INS S JOIN SZMAIN_INS M
          ON S.DEPT_CODE = M.DEPT_CODE
         AND S.JOB_DATE  = M.JOB_DATE
         AND S.JOB_SEQ   = M.JOB_SEQ
        JOIN SZACBIF_INS A
          ON M.DEPT_CODE = A.DEPT_CODE
         AND M.ACC_NO    = A.ACC_NO
        JOIN SUUSER_TBL U
          ON M.DEPT_CODE = U.DEPT_CODE
         AND M.EMP_ID    = U.USER_ID
        JOIN SZREPIF_INS R
          ON M.REPORT_CODE = R.REPORT_CODE) SNT
  ON SND.DEPT_CODE      = SNT.DEPT_CODE
 AND SND.SND_DATE       = SNT.SND_DATE
 AND SND.CUR_TOT_SEQ_NO = SNT.CUR_TOT_SEQ_NO
JOIN SCFAXIMG_TBL IMG
  ON SND.DEPT_CODE  = IMG.DEPT_CODE
 AND SND.SND_DATE   = IMG.SND_DATE
 AND SND.TRADE_DATE = IMG.TRADE_DATE
 AND SND.IDX_SEQ_NO = IMG.IDX_SEQ_NO
JOIN SZACBIF_INS ACB
  ON SNT.DEPT_CODE = ACB.DEPT_CODE
 AND SNT.ACC_NO    = ACB.ACC_NO
WHERE SND.SND_DATE = '20180214'
  AND SND.FROM_PARTY_ID = 'PARTYID'
  AND SND.DEPT_CODE = '10' 
  AND IMG.SEC_TYPE = 'Z'

-- E-MAIL
-- SCMELSND_TBL SND
-- SZMELSNT_INS SNT
-- SCMELATT_TBL ATT
SELECT SEND_TYPE = 'E-mail', SNT.JOB_SEQ, SNT.EMP_ID, SNT.USER_NAME,
       SNT.FULL_ACC_NO, SNT.ACC_NO, SNT.PRD_NO, SNT.BLC_NO, SNT.ACC_NAME_KOR,
       F_RCV_NAME_KOR = '', MEDIA_NO = '',
       E_RCV_NAME_KOR = '', RCV_MAIL_ADDR = '',
       SNT.REPORT_CODE, SNT.REPORT_ID, SNT.VIEW_FILENAME, 
       SUBJECT_DATA = SND.SUBJECT_DATA, 
       MAIL_BODY_DATA = CONVERT(VARCHAR(8000), SND.MAIL_BODY_DATA), 
       SND.SEND_TIME, SND.SENT_TIME,
       SND.SND_DATE, SND.DIFF_TIME, DIRECTION = '', TOTAL_PAGES = 0,
       SEND_PAGE = 0, BUSY_RESND_CNT = 0, SND.RSP_FLAG, SND.CUR_TOT_SEQ_NO, 
       SND.ERR_CODE, SND.EXT_MSG, SND.OPR_ID, SND.OPR_TIME 
FROM SCMELSND_TBL SND 
JOIN (SELECT S.*, 
               FULL_ACC_NO = (CASE WHEN M.PRD_NO = '' THEN M.ACC_NO
                                   ELSE (CASE WHEN M.BLC_NO = '' THEN M.ACC_NO + '-' + M.PRD_NO
                                              ELSE M.ACC_NO + '-' + M.PRD_NO + '-' + M.BLC_NO
                                         END)
                              END), A.ACC_NAME_KOR,
               M.ACC_NO, M.PRD_NO, M.BLC_NO, M.JOB_TIME, M.EMP_ID, U.USER_NAME,
               R.REPORT_CODE, R.VIEW_FILENAME,
               REPORT_ID = ISNULL((SELECT RI.REPORT_ID
                                   FROM SZREPID_INS RI
                                   WHERE R.REPORT_CODE = RI.REPORT_CODE), R.REPORT_CODE)
        FROM SZMELSNT_INS S JOIN SZMAIN_INS M
          ON S.DEPT_CODE = M.DEPT_CODE
         AND S.JOB_DATE  = M.JOB_DATE
         AND S.JOB_SEQ   = M.JOB_SEQ
        JOIN SZACBIF_INS A
          ON M.DEPT_CODE = A.DEPT_CODE
         AND M.ACC_NO    = A.ACC_NO
        JOIN SUUSER_TBL U
          ON M.DEPT_CODE = U.DEPT_CODE
         AND M.EMP_ID    = U.USER_ID
        JOIN SZREPIF_INS R
          ON M.REPORT_CODE = R.REPORT_CODE) SNT
  ON SND.DEPT_CODE      = SNT.DEPT_CODE
 AND SND.SND_DATE       = SNT.SND_DATE
 AND SND.CUR_TOT_SEQ_NO = SNT.CUR_TOT_SEQ_NO
JOIN SCMELATT_TBL ATT
  ON SND.SND_DATE = ATT.SND_DATE
 AND SND.CUR_TOT_SEQ_NO = ATT.CUR_TOT_SEQ_NO
JOIN SZACBIF_INS ACB
  ON SNT.DEPT_CODE = ACB.DEPT_CODE
 AND SNT.ACC_NO    = ACB.ACC_NO
WHERE SND.SND_DATE = '20180214'
  AND SND.DEPT_CODE = '10' 